export const defaultSEO = {
  title: "Sohib Khan — Full Stack QA Intern & Automation Specialist",
  description:
    "QA Engineer dedicated to breaking software so users don't have to. Specializing in manual validation, functional testing, Selenium, Playwright, and Postman API testing.",
  baseUrl: "https://sohibkhan.vercel.app",
  metadataBase: new URL("https://sohibkhan.vercel.app"),
  author: "Sohib Khan",
  siteName: "Sohib Khan Portfolio",
  ogImage: "https://sohibkhan.vercel.app/og-image.jpg",
  ogImageAlt: "SK Sohib Khan — Software Tester & Full Stack QA Specialist",
  twitterCreator: "@SohibKhan",
  keywords: [
    "Sohib Khan",
    "QA Intern",
    "QA Engineer",
    "QA Automation Engineer",
    "Software Tester",
    "Automation Testing",
    "Manual Testing",
    "Selenium WebDriver",
    "Playwright",
    "API Testing",
    "Postman",
    "Artifact Geeks",
    "Core Java",
    "JavaScript",
    "MySQL",
    "MongoDB",
    "Quality Assurance",
    "Next.js Portfolio",
    "Test Automation Specialist",
    "Web Application Testing",
    "Cross Browser Testing",
  ],
};
